name: Run All Tests

on: workflow_dispatch

env:
  OPENBLAS_NUM_THREADS: 1
  OMP_NUM_THREADS: 1

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest'] # [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ['3.10','3.11','3.12','3.13']

    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
      - run: Rscript -e 'print("hello")'
      - uses: actions/checkout@v4
      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install dev dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: Handle eigen
        run: git submodule update --init --recursive
      - name: Build package
        run: pip install -e .
      - name: Install R packages for pytest
        run: python tests/install_R.py
      - name: Test
        run: pytest
      - name: Run all jupyter examples
        run: python examples/run_examples.py
